#!/usr/bin/env python3
"""Splits demo/walkthrough.tape into per-act tape files at its
`# ACT-BOUNDARY: N` markers, each a self-contained VHS tape (shared
header + Hide-setup block, then that act's slice of commands) rendering
to media/acts/cli-actN.mp4. Used to build a finer-grained interleave
with the dashboard capture than compose_full_video.sh's two-act cut --
see compose_interleaved_video.sh.

walkthrough.tape stays the single source of truth for the CLI commands;
this only slices it. Re-run whenever walkthrough.tape's commands or
ACT-BOUNDARY markers change.
"""
import re
from pathlib import Path

DEMO_DIR = Path(__file__).resolve().parent.parent
TAPE = DEMO_DIR / "walkthrough.tape"
ACTS_DIR = DEMO_DIR / "media" / "acts"

GENERATED_NOTE = (
    "# Auto-generated by media/split_tape_into_acts.py from ../walkthrough.tape.\n"
    "# Do not hand-edit -- edit walkthrough.tape (its Require/Set lines, or its\n"
    "# ACT-BOUNDARY markers) instead and re-run the splitter.\n\n"
)


def main():
    text = TAPE.read_text()

    # Preamble = everything from "Require bash" through the Hide-setup
    # block's closing "Show" -- extracted verbatim from the master tape
    # (not duplicated here) so Set Width/Height/Theme/etc. can't drift
    # between the master tape and the generated acts.
    preamble_start = text.index("Require bash")
    setup_end = text.index("Show\n", preamble_start) + len("Show\n")
    preamble = text[preamble_start:setup_end]

    body = text[setup_end:].lstrip("\n")
    parts = re.split(r"\n# ACT-BOUNDARY: \d+\n", body)
    ACTS_DIR.mkdir(parents=True, exist_ok=True)

    for i, part in enumerate(parts, start=1):
        tape_path = ACTS_DIR / f"act{i}.tape"
        content = (
            GENERATED_NOTE
            + f"Output demo/media/acts/cli-act{i}.mp4\n\n"
            + preamble
            + "\n"
            + part.strip()
            + "\n"
        )
        tape_path.write_text(content)
        print(f"wrote {tape_path.relative_to(DEMO_DIR.parent)}")

    print(f"\n{len(parts)} acts. Render each: for f in demo/act*.tape; do vhs \"$f\"; done")


if __name__ == "__main__":
    main()
